//POST http://localhost:8080/api/expenses
//ntent-Type: application/json

//{
  //"amount": 50,
  //"category": "food",
  //"date": "2026-06-01",
  //"user": { "id": 1 }
//}
GET http://localhost:8080/api/summary/user/1
