spring.application.name=spendbijak
spring.datasource.url= jdbc:postgresql://localhost:5432/spendbijak
spring.datasource.username=postgres
spring.datasource.password=Admin123

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true


